# Generated by Django 4.1.7 on 2024-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie1_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie1',
            name='image',
            field=models.ImageField(default='fghlk', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
