# Generated by Django 4.1.7 on 2024-03-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie1_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie1',
            old_name='image',
            new_name='img',
        ),
    ]
